replicaCount: 1

image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

fullnameOverride: weatherlookup-postgres

auth:
  existingSecret: ""
  username: weatherlookup
  password: weatherlookup-local
  database: weatherlookup

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 2Gi
  storageClassName: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}
